#!/usr/bin/env python3.7

fahrenhieit = float(input("What temprrature (in Fahrenit ) would you like to be converted"))
celsius = (fahrenhieit - 32) *  5 / 9 

print(fahrenhieit. "F is ", round(celsius, 2) "C")
